// ── Colour palette ────────────────────────────────────────────────────────────
export const P = {
  bg:"#0a0a0f", surface:"#12121a", card:"#1a1a26", border:"#2a2a40",
  accent:"#f0a500", accentDim:"#f0a50033",
  gold:"#d4875a", teal:"#3dd6c8", tealDim:"#3dd6c820",
  muted:"#6b6b8a", text:"#e8e8f0", textSoft:"#a0a0c0",
  red:"#e05c5c", green:"#4ecb71", purple:"#b06dff",
};

// ── Reference types ───────────────────────────────────────────────────────────
export const REF_TYPES = {
  original_recording: { label:"Original Recording", color:P.teal,   icon:"▶" },
  tutorial:           { label:"Tutorial",            color:P.purple, icon:"🎸" },
  lesson:             { label:"Lesson",              color:P.accent, icon:"📖" },
  chord_chart:        { label:"Chord Chart",         color:P.gold,   icon:"♩" },
  live_performance:   { label:"Live Performance",    color:P.green,  icon:"🎤" },
};

// ── Source quality ────────────────────────────────────────────────────────────
export const SOURCE_QUALITY = {
  verified:    { label:"Source Verified", color:P.teal,   icon:"✓", desc:"Built from published sheet music or chord songbook" },
  ai_assisted: { label:"AI Assisted",     color:P.purple, icon:"✦", desc:"Generated by Claude — verify against recording" },
  manual:      { label:"Manual Entry",    color:P.gold,   icon:"✎", desc:"User-entered — accuracy depends on source used" },
  builtin:     { label:"Built-in",        color:P.teal,   icon:"●", desc:"Pre-loaded song" },
};

// ── Embellishment types ───────────────────────────────────────────────────────
export const EMBELLISHMENT_TYPES = {
  bend:    { label:"b",  color:P.accent, desc:"Push string up (or down) to raise pitch" },
  slide:   { label:"sl", color:P.teal,   desc:"Glide finger from one fret to another" },
  hammer:  { label:"h",  color:P.green,  desc:"Hammer-on: sound note without picking" },
  pull:    { label:"p",  color:P.purple, desc:"Pull-off: pluck with fretting finger" },
  vibrato: { label:"~",  color:P.gold,   desc:"Oscillate pitch slightly for expression" },
  mute:    { label:"x",  color:P.muted,  desc:"Palm or fret-hand mute for percussive hit" },
};

// ── Feel info ─────────────────────────────────────────────────────────────────
export const FEEL_INFO = {
  straight: { label:"Straight",  color:P.teal,   desc:"Even eighth or sixteenth notes — no swing" },
  swung:    { label:"Swung",     color:P.gold,   desc:"Delay every second eighth note slightly — shuffled feel" },
  triplet:  { label:"Triplet",   color:P.purple, desc:"Three evenly spaced notes per beat" },
  shuffle:  { label:"Shuffle",   color:P.accent, desc:"Heavy swing — first note long, second short" },
};

// ── localStorage keys (sc7_ prefix — must never change) ──────────────────────
export const LS_SONGS    = "sc7_songs";
export const LS_PROGRESS = "sc7_progress";
export const LS_SESSION  = "sc7_session";
export const LS_SEMIS    = "sc7_semitones";
